#!/bin/bash

# Verifica se o arquivo composer.json existe
if [ -f /var/www/composer.json ]; then
    # Lê o valor de APP_ENV do arquivo .env
    if [ -f /var/www/.env ]; then
        APP_ENV=$(grep -E '^APP_ENV=' /var/www/.env | cut -d '=' -f2 | tr -d '"')
    fi

    # Verifica o ambiente e executa os comandos apropriados
    if [ "$APP_ENV" = "production" ]; then
        echo "Ambiente de produção detectado. Executando comandos para produção..."
        composer clear-cache
        composer install --no-dev --optimize-autoloader --prefer-dist --no-interaction --no-progress
        php artisan migrate --force
        php artisan config:cache
        php artisan route:cache
        php artisan view:cache
        php artisan storage:link
        php artisan optimize:clear
    else
        echo "Ambiente de desenvolvimento detectado. Executando comandos para desenvolvimento..."
        composer clear-cache
        composer install --optimize-autoloader --prefer-dist --no-interaction --no-progress
        php artisan migrate
        php artisan config:clear
        php artisan route:clear
        php artisan view:clear
        php artisan storage:link
    fi

    # Comandos comuns para ambos os ambientes
    php artisan filament:optimize
else
    echo "Arquivo /var/www/composer.json não encontrado. Comandos ignorados."
fi

# Iniciar o Supervisor
exec /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
